---
- name: Identify reachable hosts
  hosts: all
  connection: local
  gather_facts: false
  strategy: linear

  tasks:
    - block:
        - name: determine hosts that are reachable
          ansible.builtin.wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "reachable" group
          ansible.builtin.group_by:
            key: reachable
      rescue:
        - name: debug print unreachable host(s)
          ansible.builtin.debug: msg="cannot connect to {{ inventory_hostname }}"
