- hosts: all
  gather_facts: yes
  become: false
  tasks:
    - name: Save Distro info
      set_fact:
        os_distro: "{{ ansible_distribution }}"
        os_version: "{{ ansible_distribution_version }}"
        os_major: "{{ ansible_distribution_major_version }}"
        cacheable: yes
    
    - name: System details
      debug: msg="{{ item }}"
      with_items:

        - "{{ os_distro }}"
        - "{{ os_version }}"
        - "{{ os_major }}"
