"""=======================================================================

Author: Rob Jackson

Parses subnet scan data (from ./json_hosts_data) generated by scan.py (nmap plugin scans),
generating an inventory file for use with gather_facts

=========================================================================="""

# Import the json and configparser modules
import configparser
import json
import os
import pathlib as p
import shutil
from datetime import datetime

debug = True
#debug = False

#GLOBAL_FILE_JSON = "/home/rjackson/dynamic_inventory_live/hosts.json"
#GLOBAL_FILE_INVENTORY = "/home/rjackson/dynamic_inventory_live/inventory"
#GLOBAL_DIRECTORY_HOSTS = "/home/rjackson/dynamic_inventory_live/hosts"
#GLOBAL_DIRECTORY_HOSTS_CSV = "/ansible/csv"
#GLOBAL_DIRECTORY_JSON_DATA = "/home/rjackson/dynamic_inventory_live/json_hosts_data"
#GLOBAL_FILE_HOSTS_CSV = "/ansible/csv/hosts.csv"

GLOBAL_FILE_JSON = "/home/rjackson/dynamic_inventory_live_dev/hosts.json"
GLOBAL_FILE_INVENTORY = "/home/rjackson/dynamic_inventory_live_dev/inventory"
GLOBAL_DIRECTORY_HOSTS = "/home/rjackson/dynamic_inventory_live_dev/hosts"
GLOBAL_DIRECTORY_HOSTS_CSV = "/home/rjackson/dynamic_inventory_live_dev/csv"
GLOBAL_DIRECTORY_JSON_DATA = "/home/rjackson/dynamic_inventory_live_dev/json_hosts_data"
GLOBAL_FILE_HOSTS_CSV = "/home/rjackson/dynamic_inventory_live_dev/csv/hosts.csv"

def get_timestamp() -> str:
    return datetime.now().isoformat(sep=" ")


# Define a function to load JSON data from a file
def load_json(file):
    if debug:
        print("[%s] using file: %s" % (get_timestamp(), file))
    # Open the file in read mode
    with open(file, "r") as f:
        # Load the JSON data and return it
        data = json.load(f)
        return data


# Define a function to write data to a file
def write_inventory(data, file):
    myfindings = {}
    devices = []
    iplist = []
    # Create a ConfigParser object
    config = configparser.ConfigParser()
    # Loop through the data
    for key, value in data.items():
        # Check if the key is _meta
        if key == "_meta":
            # Skip this key as it is not needed for the hosts file
            myfindings = list(data.items())[0][1]["hostvars"]
            for k in myfindings:
                curdict = myfindings[k]
                # only configure for host entry if there's a host name to work with.
                if curdict["ip"] != curdict["name"]:
                    devices.append(curdict)
                    # if debug: print(curdict)
                iplist.append(curdict["ip"])
            continue
    if debug:
        print("\nfindings: ", myfindings)
    with open(file, "w") as f:
        # Write the data to the file
        for d in devices:
            # write out individual host entries for anything with a host name.
            f.write("\n[%s]\n" % d["name"])
            f.write("%s\n" % d["ip"])
        # write out all ip's to their own section
        f.write("\n[devices]\n")
        for entry in iplist:
            f.write("%s\n" % entry)

    # create hosts directory for gather_facts to write to.
    initialize_directory(GLOBAL_DIRECTORY_HOSTS)
    # create directory for gather_facts to write hosts.csv
    initialize_directory(GLOBAL_DIRECTORY_HOSTS_CSV)


# Define a function to write data to a file
def write_inventory2(directory_json_data, file_inventory):
    myfindings = {}
    devices = []
    iplist = []
    # Create a ConfigParser object
    # config = configparser.ConfigParser()

    if debug:
        print("[%s] using json hosts data: %s" % (get_timestamp(), directory_json_data))

    # iterate through each json data file:
    for json_host_file in os.listdir(directory_json_data):
        if debug:
            print("[%s] using json_host_file %s:" % (get_timestamp(), json_host_file))
        data = load_json("%s/%s" % (GLOBAL_DIRECTORY_JSON_DATA, json_host_file))
        # Loop through the data
        for key, value in data.items():
            # Check if the key is _meta
            if key == "_meta":
                # Skip this key as it is not needed for the hosts file
                myfindings = list(data.items())[0][1]["hostvars"]
                for k in myfindings:
                    curdict = myfindings[k]
                    # only configure for host entry if there's a host name to work with.
                    if curdict["ip"] != curdict["name"]:
                        devices.append(curdict)
                        # if debug: print(curdict)
                    iplist.append(curdict["ip"])
                continue

    # if ./inventory found, delete it.
    if os.path.exists(file_inventory):
        if debug:
            print("[%s] Discovered out of data inventory: %s" % (get_timestamp(), file_inventory))
        os.remove(file_inventory)
        if debug:
            print("[%s] Deleted out of data inventory: %s" % (get_timestamp(), file_inventory))
    # create inventory file
    if debug:
        print("\n[%s] findings: %s" % (get_timestamp(), devices))
        print("[%s] writing inventory file: %s" % (get_timestamp(), file_inventory))
    with open(file_inventory, "w") as f:
        # Write the data to the file
        for d in devices:
            # write out individual host entries for anything with a host name.
            f.write("\n[%s]\n" % d["name"])
            f.write("%s\n" % d["ip"])
        # write out all ip's to their own section
        f.write("\n[devices]\n")
        for entry in iplist:
            f.write("%s\n" % entry)
        if debug:
            print("[%s] Total # of ip's: %i" % (get_timestamp(), len(iplist)))

def delete_directory(directory_path):
    try:
        shutil.rmtree(directory_path)
        if debug:
            print("[%s] Deleted directory: %s" % (get_timestamp(), directory_path))
    except OSError as e:
        print("[%s] Error: %s : %s" % (get_timestamp(), directory_path, e.strerror))


def prep_gather_facts(directory_hosts_csv, file_hosts_csv, directory_hosts):
    # create hosts directory for gather_facts to write hosts
    initialize_directory(directory_hosts)

    # create directory for gather_facts to write hosts.csv
    initialize_directory(directory_hosts_csv)

    # create hosts.csv
    csv_full_filepath = p.Path(file_hosts_csv)
    csv_full_filepath.touch()
    if debug:
        print("[%s] Initialized file: %s" % (get_timestamp(), csv_full_filepath))


def initialize_directory(directory_path):
    path_directory_path = p.Path(directory_path)
    if path_directory_path.exists():
        if debug:
            print("[%s] Found directory: %s" % (get_timestamp(), directory_path))
        delete_directory(directory_path)
    path_directory_path.mkdir()
    if debug:
        print("[%s] Initialized directory: %s" % (get_timestamp(), directory_path))


# Define a main function
def main():
    # Get the JSON file name from the user input or use the default
    # json_file = input("Enter the JSON file name: ") or "./hosts.json"
    # Get the INI file name from the user input or use the default
    # ini_file = input("Enter the INI file name: ") or "./hosts.ini"
    # Call the load_json function and get the JSON data
    # json_data = load_json(json_file)
    # Call the write_ini function and write the INI data to the file
    # write_inventory(json_data, inventory_file)

    # bulk load all hosts files from json_hosts_data dir
    write_inventory2(GLOBAL_DIRECTORY_JSON_DATA, GLOBAL_FILE_INVENTORY)
    prep_gather_facts(
        GLOBAL_DIRECTORY_HOSTS_CSV, GLOBAL_FILE_HOSTS_CSV, GLOBAL_DIRECTORY_HOSTS
    )
    # Print a success message
    # if debug: print(f"Successfully converted {json_file} to {inventory_file}")


# Check if the script is run as the main module
if __name__ == "__main__":
    # Call the main function
    main()
