#- hosts: dynamicOS
- hosts: all
  become: true
  vars_files:
    - "dynamicos/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  tasks:
    - name: Save Distro info
      set_fact:
        os_distro: "{{ ansible_distribution }}"
        os_version: "{{ ansible_distribution_version }}"
        os_major: "{{ ansible_distribution_major_version }}"
        cacheable: yes
  tasks:
    - package:
        name: "{{ package_name }}"
        state: present
